# Generated by Django 6.1.1 on 2026-09-14 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('profissional_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_1', to='atendimentos.profissional')),
                ('profissional_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_2', to='atendimentos.profissional')),
            ],
            options={
                'ordering': ['dia_semana', 'horario', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimentos.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuarios',
            field=models.ManyToManyField(related_name='grupos', through='atendimentos.Participacao', to='atendimentos.usuario'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('P', 'Presença'), ('F', 'Falta'), ('FJ', 'FJ'), ('AF', 'Atendimento Familiar'), ('AE', 'Atendimento Extra')], max_length=2)),
                ('observacao', models.CharField(blank=True, max_length=250)),
                ('registrado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimentos.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimentos.usuario')),
            ],
            options={
                'ordering': ['data', 'grupo__horario', 'usuario__nome_completo'],
                'constraints': [models.UniqueConstraint(fields=('data', 'grupo', 'usuario'), name='registro_diario_unico')],
            },
        ),
        migrations.AddConstraint(
            model_name='participacao',
            constraint=models.UniqueConstraint(fields=('grupo', 'usuario'), name='participacao_unica'),
        ),
    ]
